# PHP CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            sudo apt install apt-transport-https ca-certificates curl software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
            apt-cache policy docker-ce
      - run:
          name: Install Docker Compose
          command: |
            set -x
            sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose up -d
      - deploy:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST
            cd /home/ng/web/
            git clone git@github.com:NicolaeGrigoriu/b1b.git
            cd b1b
            composer install
